export const CHANGE_SPIDER_POSITION = 'CHANGE_SPIDER_POSITION';
export const CHECK_INTERSECTION = 'CHECK_INTERSECTION';
export const CHECK_IS_COMPLETED = 'CHECK_IS_COMPLETED';
export const REPLAY = 'REPLAY';
export const NEXT_ROUND = 'NEXT_ROUND';
export const PREV_ROUND = 'PREV_ROUND';
